default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do |options|
    # CI 환경 설정
    setup_ci

    # App Store Connect API Key 설정 (GitHub Secrets에서 가져옴)
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"], # .p8 파일 내용
      is_key_content_base64: true, # base64로 인코딩해서 넣을 예정
      in_house: false
    )

    # 인증서 동기화 (Match) - 읽기 전용 (배포 시에는 생성하지 않음)
    match(
      type: "appstore",
      readonly: true,
      api_key: api_key,
      team_id: "8UY99NV2AM",
      app_identifier: ["com.koach.app"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )
		if options[:build_number]
      increment_build_number(
        build_number: options[:build_number],
        xcodeproj: "App/App.xcodeproj"
      )
    end

		# ios 빌드 버전
		increment_version_number(
  	version_number: "1.4.2", # 원하는 버전 명시
  	xcodeproj: "App/App.xcodeproj"
			)

		# Xcode의 자동 서명을 끄고 수동 서명으로 변경
		update_code_signing_settings(
      use_automatic_signing: false,
      targets: ["App"],
      path: "App/App.xcodeproj", # 프로젝트 파일 경로
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "com.koach.app",
      profile_name: "match AppStore com.koach.app", # match로 받은 프로파일 이름
			team_id: "8UY99NV2AM"
    )

    # 앱 빌드 (Gym)
    gym(
      scheme: "App",
      workspace: "App/App.xcworkspace",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.koach.app" => "match AppStore com.koach.app"
        }
      }
    )

    # TestFlight 업로드 (Pilot)
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
  
  # === 인증서 최초 생성용 Lane ===
  desc "Generate Certificates on CI"
  lane :generate_certs do
    setup_ci
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    # 인증서 생성 및 git repo에 push (readonly: false)
    match(
      type: "appstore",
      readonly: false,
      api_key: api_key,
      app_identifier: ["com.koach.app"],
      force: true,
      team_id: "8UY99NV2AM",
      skip_certificate_matching: true,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"] 
    )
  end
end
