const ServicePolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto  text-gray-800 leading-relaxed">
      <div className="mb-10">
        <div className="text-2xl text-display mb-3">
          K-oach Terms of Service
        </div>
        <div className="mb-3">
          <p className="text-body text-sm">
            Effective Date: February 1, 2026 (Example)
          </p>
          <p className="text-body text-sm">
            Operating Entity: K-oach Operator (hereinafter "the Company")
          </p>
          <p className="text-body text-sm">
            Responsible Officer (Representative): Yu seojeong
          </p>
          <p className="text-body text-sm">
            Customer Service Email: info.koach11@gmail.com
          </p>
        </div>

        <p className="text-body text-sm">
          These Terms of Service (hereinafter "Terms") govern the rights,
          obligations, and responsibilities of the Company and its Members, as
          well as other necessary matters concerning the use of the K-oach
          service (hereinafter "the Service") provided by the K-oach Operator
          (hereinafter "the Company").
        </p>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">Article 1 (Purpose)</div>
        <p className="text-body text-sm">
          The purpose of these Terms is to define the fundamental rights,
          obligations, responsibilities, and conditions and procedures for
          service use between the Company and its Members.
        </p>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 2 (Definitions)
        </div>
        <ul className="text-body text-sm list-disc list-inside space-y-3">
          <li>
            Member: Refers to an individual who agrees to these Terms and the
            Personal Information Processing Policy, creates an account, and uses
            the Service.
          </li>
          <li>
            Service: Refers to the Korean conversation AI chatbot service
            provided through the K-oach app and all accompanying functions. The
            Service does not provide features for user-to-user interaction or
            content sharing; users can only utilize text-based chat. This
            includes services that allow continuous use by transferring account
            and data from existing web services (e.g., "Dorandoran") operated by
            the same entity without separate registration.
          </li>
          <li>
            Account: Refers to a unit of membership created for member
            identification and service use.
          </li>
          <li>
            Account Information: Refers to information necessary for account
            creation, maintenance, security, and service provision (email (ID),
            password, name, date of birth, personal question/answer, consent
            history, etc.).
          </li>
          <li>
            Content: Refers to text, data, UI, logos, etc., provided or
            displayed within the Service, as well as data entered by members or
            generated during use (chat messages, saved items, inquiry/report
            details, etc.), and responses generated by AI (including
            corrections/word explanations).
          </li>
        </ul>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 3 (Effectiveness, Application, and Amendment of the Terms)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            The Company shall post these Terms on the service's Terms screen,
            making them easily accessible to Members.
          </li>
          <li>
            The Company may amend these Terms to the extent that it does not
            violate relevant laws. In case of amendment, the Company shall
            specify the effective date and reasons for amendment, and notify
            Members through announcements on the service screen, pop-up notices,
            push notifications, or emails, at least 7 days prior to the
            effective date (30 days prior for amendments unfavorable to
            Members).
          </li>
          <li>
            If a Member continues to use the Service without explicitly
            expressing disagreement by the effective date of the amended Terms,
            it shall be deemed that the Member has consented to the amended
            Terms.
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 4 (Commencement of Service Use)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            Members can register through one of the following methods:
            <ul className="list-disc list-inside mb-3 ml-4">
              <li>
                In-app Registration: Agreement to Terms/Personal Information
                Processing Policy/Marketing (optional)/Age 14 or older → Entry
                of Name/Date of Birth/Email (ID)/Password → Setting a personal
                question.
              </li>
              <li>
                Google Account Registration: Registration and authentication via
                Google Account → Agreement to Terms/Personal Information
                Processing Policy/Marketing (optional)/Age 14 or older →
                Collection of Date of Birth.
              </li>
              <li>
                Transfer of Existing Web Service Account Information: Automatic
                login to the K-oach app is possible with an account created on
                an existing web service (e.g., "Dorandoran") operated by the
                same entity, without separate registration (for the purpose of
                fulfilling the service usage agreement).
              </li>
            </ul>
          </li>
          <li>
            The Company does not permit the registration of members under 14
            years of age (age 14 or older verification required during the
            registration process).
          </li>
        </ol>
      </div>

      <div>
        <div className="text-display text-2xl mb-3">
          Article 5 (Service Provision)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            The Company provides the following services to Members:
            <ul className="list-disc list-inside mb-3 ml-4">
              <li>
                AI chatbot conversation (Chat rooms: Friend, Honey, coworker,
                senior, service manager).
              </li>
              <li>
                Selection of intimacy level (Polite (reserved & awkward) /
                Friendly (close & casual)) and language correction tailored to
                the intimacy level.
              </li>
              <li>
                Provision of AI responses, correction messages, and word
                explanations.
              </li>
              <li>
                TTS (Text-to-Speech) voice playback for AI responses,
                corrections, and word explanations.
              </li>
              <li>
                Saving to "Saved" (sentences/words), filtering by
                concept/intimacy, deletion, and TTS playback.
              </li>
              <li>AI response reporting function (flag icon).</li>
              <li>
                Inquiry chat room (service manager) for submitting inquiries and
                (optional) submitting a reply email.
              </li>
              <li>
                Onboarding survey (acquisition channel/Korean proficiency
                level/purpose of Korean conversation/interests/notification
                subscription).
              </li>
            </ul>
          </li>
          <li>
            The Service does not provide camera/microphone for photo/recording
            functions, and Members can only use the Service through text-based
            chat. Members cannot send or post content in the form of images,
            videos, or any other non-text content within the Service.
          </li>
          <li>
            Free Provision and Future Monetization Potential
            <ul>
              <li className="list-disc list-inside mb-4 ml-4">
                Currently, the K-oach Service provides all functions free of
                charge. However, the Company may, according to its operational
                policy, introduce a monetization policy for some or all
                functions in the future. In such cases, the Company shall
                establish separate Terms of Service for paid services and apply
                them after prior notice to and consent from the Member.
              </li>
            </ul>
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 6 (Protection and Use of Personal Information)
        </div>
        <ol className="text-body text-sm list-decimal list-inside  space-y-3">
          <li>
            The Company abides by laws related to personal information
            protection, and matters concerning personal information processing
            are governed by the Personal Information Processing Policy.
          </li>
          <li>
            Email addresses are used for (a) member identification and login ID,
            (b) transfer of account information and automatic login between the
            existing web service and the K-oach app, and (c) for purposes of
            account protection and customer support such as service
            notifications (updates/policy changes), inquiry replies, password
            resets, and account retrieval.
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 7 (Management and Amendment of Personal Information)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            Members can amend some information, such as interests and
            notification settings, within the scope provided by the Service.
          </li>
          <li>
            Members are responsible for keeping their account information
            up-to-date and accurate.
          </li>
          <li>
            If account theft is suspected, Members must immediately change their
            password and notify the Company through inquiry.
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 8 (Use of Content)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            Members may use AI responses (including corrections/explanations) as
            reference material for learning. However, the Company does not
            guarantee the accuracy, completeness, reliability, or fitness for a
            particular purpose of all content generated by AI, and is not
            responsible for any damages resulting therefrom.
          </li>
          <li>
            Members may use the Service for personal and non-commercial purposes
            only, and may not copy, distribute, transmit, or create derivative
            works of content within the Service (logos, UI, system messages,
            etc.) without the prior consent of the Company.
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 9 (Changes and Suspension of Service)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            The Company may change all or part of the Service as required for
            operational or technical reasons.
          </li>
          <li>
            The provision of the Service may be temporarily suspended in
            unavoidable circumstances such as system maintenance, failures, or
            urgent security measures, with prior notice given to the extent
            possible.
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 10 (Information Collection)
        </div>
        <p className="text-body text-sm">
          The Company may collect account information, usage information, and
          log information for the purpose of service provision and improvement,
          security, and stability (for detailed information, refer to the
          Personal Information Processing Policy). In particular, the Company
          may collect and analyze chat history between Members and the AI
          chatbot for the purpose of improving chatbot quality and enhancing AI
          performance. Collected chat history may be stored and utilized in an
          unidentifiable form for a period of 90 days during the service usage
          period. All account information and chat history will be immediately
          deleted upon member withdrawal. However, data that has been
          pseudonymized or anonymized to prevent personal identification may be
          separately stored for service improvement and statistical analysis
          purposes.
        </p>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 11 (Company's Obligations)
        </div>
        <p className="text-body text-sm">
          The Company shall comply with relevant laws and these Terms, and
          endeavor to provide stable service and protect personal information.
        </p>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 12 (Member's Obligations)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            Members shall not engage in any of the following acts:
            <ul className="list-disc list-inside mb-3 ml-4">
              <li>
                Theft or unauthorized use of another person's account
                information.
              </li>
              <li>
                Acts that interfere with service operations (e.g., causing
                abnormal traffic, using automation/scraping tools).
              </li>
              <li>
                Transmission of content that violates laws or public order and
                morals, including text content related to Child Sexual Abuse
                Material (CSAM), child exploitation, or abuse.
              </li>
              <li>
                Acts that infringe upon the rights of the Company or third
                parties (e.g., copyright infringement, defamation).
              </li>
              <li>
                Members are responsible for maintaining their account security,
                and problems arising from account sharing are, in principle, the
                Member's responsibility.
              </li>
            </ul>
          </li>
          <li>
            The Company does not permit the registration of members under 14
            years of age (age 14 or older verification required during the
            registration process).
          </li>
        </ol>
      </div>

      <div>
        <div className="text-display text-2xl mb-3">
          Article 13 (Attribution of Copyright and Use Restrictions)
        </div>
        <ol className="text-body text-sm list-decimal list-inside space-y-3">
          <li>
            Copyright and other intellectual property rights to the Service and
            content provided by the Company belong to the Company.
          </li>
          <li>
            Rights to content entered by the Member belong to the Member.
            However, the Company may use such content within the scope of
            providing/operating the Service and improving its quality, under
            protection measures in accordance with the Personal Information
            Processing Policy.
          </li>
        </ol>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 14 (Collection and Use of Personal Information)
        </div>
        <p className="text-body text-sm">
          Matters regarding the collection items, usage purposes, retention and
          usage periods, and destruction of personal information are governed by
          the Personal Information Processing Policy.
        </p>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          Article 15 (Supplementary Provisions)
        </div>
        <p className="text-body text-sm mb-10">
          Matters not stipulated in these Terms shall be governed by relevant
          laws and the operational policies announced by the Company.
        </p>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          [Appendix] K-oach Operational Policy
        </div>
        <div className="text-body text-sm">
          Effective Date: February 1, 2026 (Example)
        </div>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          1. Inquiry Chat Room (Service Manager) Operational Policy
        </div>
        <ul className="text-body text-sm list-disc list-inside space-y-3">
          <li>
            Automated Response (Scenario-based): When a Member selects an
            inquiry type, the service manager provides an automated response
            matching the type. Automated responses are for reference and may
            require further verification.
          </li>
          <li>
            Administrator Review and Email Reply (Optional): If a Member selects
            "Receive Reply" and submits a reply email, the Company will review
            the inquiry and reply via email within 15 business days.
          </li>
          <li>
            Inquiry Submission Procedure: Select inquiry type → Automated
            response → Enter detailed content → Submit → Enter reply email
            (optional) → Complete.
          </li>
        </ul>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          2. Reporting (Flag Icon) Policy
        </div>
        <ul className="text-body text-sm list-disc list-inside space-y-3">
          <li>Members can report AI responses they deem problematic.</li>
          <li>
            Upon successful reporting, a toast pop-up such as "Thank you for
            your report" will be displayed.
          </li>
          <li>
            Reported responses will be internally reviewed for service quality
            improvement. In particular, if the content is confirmed to be
            illegal or in violation of the Terms, including text content related
            to Child Sexual Abuse Material (CSAM), child exploitation, or abuse,
            it will be immediately deleted and necessary legal actions (such as
            reporting to relevant authorities) will be taken in accordance with
            relevant laws. No monetary compensation will be provided for
            reports.
          </li>
          <li>
            If repetitive or malicious reporting (e.g., spam/flooding) is
            confirmed, restrictive measures may be taken to protect the Service.
          </li>
        </ul>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          3. Push Notification (First Message) Policy
        </div>
        <ul className="text-body text-sm list-disc list-inside space-y-3">
          <li>
            Service notifications (e.g., one daily first message notification
            based on interests) may be sent only if the Member has consented to
            receive notifications during onboarding or in My Page.
          </li>
          <li>
            Members can turn off notifications at any time in My Page, and can
            also change notification permissions in OS settings.
          </li>
          <li>
            Marketing notifications will only be sent to Members who have
            separately opted-in to receive them.
          </li>
        </ul>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          4. Data Retention/Deletion Policy (Summary)
        </div>
        <ul className="text-body text-sm list-disc list-inside space-y-3">
          <li>
            Chat history (for quality improvement purposes) may be stored for a
            period of 90 days during the service usage period.
          </li>
          <li>
            Chat history and saved data will be immediately deleted upon member
            withdrawal.
          </li>
        </ul>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">
          5. Service Restriction (Sanction) Policy
        </div>
        <div className="text-body text-sm">
          The Company may take necessary measures, such as warnings, function
          restrictions, or account suspension, if any of the following acts are
          confirmed:
        </div>
        <ul className="text-body text-sm list-disc list-inside space-y-3">
          <li>Theft or unauthorized use of another person's account.</li>
          <li>
            Interference with service operation (e.g., abnormal traffic
            generation, use of automation tools).
          </li>
          <li>
            Transmission of illegal or harmful content, infringement of rights,
            harassment/spam,including text content related to Child Sexual Abuse
            Material (CSAM), child exploitation, or abuse.
          </li>
          <li>Abuse of reporting/inquiry functions (e.g., spam, flooding).</li>
        </ul>
      </div>

      <div className="mb-10">
        <div className="text-display text-2xl mb-3">6. Policy Amendment</div>
        <div className="text-body text-sm">
          In the event of amendment to the Operational Policy, the Company shall
          specify the effective date and reasons for amendment, and notify
          Members through announcements on the service screen, pop-up notices,
          push notifications, or emails, at least 7 days prior to the effective
          date (30 days prior for amendments unfavorable to Members).
        </div>
      </div>
    </div>
  )
}

export default ServicePolicy
