import React from 'react'

const ServicePolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-4 text-gray-800 leading-relaxed">
      <h2 className="text-2xl font-extrabold mb-3">Article 1 (Definitions)</h2>
      <p className="mb-4 font-semibold">
        The meanings of the terms used in these Terms and Conditions are as follows:
      </p>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          Member: Refers to a person who agrees to these Terms and Conditions and uses the Service.
        </li>
        <li>
          Service: Refers to the overall Korean language education services provided by the Company,
          including additional features such as chat, distance slider, and storage.
        </li>
        <li>
          AI Coach: Refers to an artificial intelligence system that corrects and recommends
          language expressions based on the Member’s messages.
        </li>
        <li>
          Distance Slider: Refers to an interface feature selected by the Member to adjust the sense
          of intimacy with the counterpart during a conversation. Depending on the selected level,
          the AI Coach adjusts the tone and vocabulary of the expressions.
        </li>
        <li>
          Storage: Refers to a space where the Member can store and manage desired messages or
          learning records during conversations with the AI Coach.
        </li>
        <li>Input: Refers to text messages or other data provided by the Member to the Service.</li>
        <li>
          Output: Refers to responses or results generated by the AI Coach based on the Input and
          provided to the Member.
        </li>
        <li>Content: Refers collectively to the Member’s Input and Output.</li>
        <li>
          Account: Refers to an identification unit created by the Member for using the Service,
          including login ID and authentication methods.
        </li>
        <li>
          MVP: Minimum Viable Product provided at the initial stage of the Service (a version
          meeting minimum requirements).
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 2 (Purpose)</h2>
      <p className="mb-6">
        The purpose of these Terms and Conditions is to stipulate the rights, obligations,
        responsibilities, and other necessary matters between [DoranDoran] (hereinafter “the
        Company”) and the Members in relation to the use of the Korean language education service
        (hereinafter “the Service”) provided by the Company.
      </p>

      <h2 className="text-2xl font-extrabold mb-3">Article 3 (Membership Registration)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          A user applies for membership registration by accurately filling in personal information
          in the form prescribed by the Company and agreeing to these Terms and Conditions.
        </li>
        <li>
          The Company accepts the user’s application, and once the membership registration is
          complete, the Service becomes available.
        </li>
        <li>
          However, the Company may refuse membership registration or terminate the service contract
          afterward in the following cases:
          <ul className="list-disc list-inside mb-4">
            <li>If another person’s name is stolen or false information is provided.</li>
            <li>If there are false entries, omissions, or errors in the membership application.</li>
            <li>
              If the user intends to use the Service for illegal purposes or in violation of these
              Terms and Conditions.
            </li>
          </ul>
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">
        Article 4 (Collection and Use of Personal Information)
      </h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          For the provision of the Service, the Company necessarily collects the following personal
          information upon membership registration:
          <ul className="list-disc list-inside mb-4">
            <li>Last name</li>
            <li>First name</li>
            <li>E-mail</li>
            <li>Password</li>
            <li>Nickname</li>
            <li className="ml-4">
              The nickname is set identical to the Last name entered during membership registration.
            </li>
          </ul>
        </li>
        <li>
          The collected personal information is used only for purposes such as membership
          registration and login, identity verification, service provision and operation, feature
          improvement, and provision of event and marketing information (upon consent).
        </li>
        <li>
          The Company complies with the Personal Information Protection Act and other relevant laws
          and regulations, and details regarding personal information protection are governed by a
          separate Privacy Policy.
        </li>
        <li>
          Upon membership withdrawal or expiration of the statutory retention period, the Member’s
          personal information is immediately destroyed
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 5 (Management of Member Information)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          For stable operation of the Service, the Last name, First name, Nickname, and E-mail set
          once cannot be modified. However, the password can be modified at any time.
        </li>
        <li>
          The Member must thoroughly manage their account information (ID, password) and may not
          transfer or lend it to others.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 6 (Use of Service)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>The Member can send and receive text messages through the 1:1 chat function.</li>
        <li>Message length is limited to 80 characters in Korean and 150 characters in English.</li>
        <li>
          The AI Coach recommends and corrects expressions appropriate to the situation and context,
          limited to language expression correction.
        </li>
        <li>
          If the Member closes or leaves the chatroom, the conversation contents of that chatroom
          are immediately deleted.
        </li>
        <li>
          However, expressions saved in the Storage by the Member are not deleted and can continue
          to be checked in the Storage.
        </li>
        <li>AI Coaching does not provide professional advice such as legal or medical.</li>
        <li>
          The Member acknowledges that the final judgment and responsibility regarding the results
          of AI Coaching rest with themselves, and the Company bears no responsibility for any acts
          based on the AI responses.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 7 (Content)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          Your Content: The Member may provide Input (“Input”) to the Service and receive Output
          (“Output”) based on it. Input and Output are collectively referred to as “Content.” The
          Member is solely responsible for the Content and must hold all necessary rights to provide
          it.
        </li>
        <li>
          Ownership: The Member retains ownership of the Input, and the Output also belongs to the
          Member. If the Company holds any rights or ownership over the Output, it transfers them to
          the Member.
        </li>
        <li>
          Similarity: Due to the nature of AI, Output may not be original, and other users may
          receive similar Output.
        </li>
        <li>
          Use by the Company: The Company may use Content for service provision, maintenance,
          improvement, legal compliance, policy enforcement, and security assurance.
        </li>
        <li>
          Right to Refuse: The Member may refuse the use of Content for model training through
          customer support procedures. In such cases, certain features may be limited.
        </li>
        <li>
          Accuracy: Output may not always be accurate or complete, and the Member is responsible for
          reviewing and using the Output. In particular, Output may not be directly used for legal,
          medical, or critical decision-making.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 8 (Data Storage and Use)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          Members’ chat messages are stored on servers for service provision and quality improvement
          and are retained for six months by default.
        </li>
        <li>
          Conversation data may be used to improve AI models after being de-identified and
          anonymized.
        </li>
        <li>
          Sensitive information (political orientation, health, finance, etc.) cannot be entered,
          and if entered, it will not be stored or used.
        </li>
        <li>
          Consent to data use can be withdrawn at any time, and the procedure follows the Privacy
          Policy.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 9 (Membership Withdrawal)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          The Member may withdraw at any time through the procedure provided within the Service.
        </li>
        <li>
          Upon withdrawal, the Member’s personal information and data are immediately destroyed in
          accordance with relevant laws and the Privacy Policy
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 10 (Termination of Service)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          The Company may terminate the provision of the Service at any time at its sole discretion
          and will notify the Member in advance or afterward.
        </li>
        <li>
          Upon termination of the Service, all rights of the Member expire, and the Company does not
          provide any separate compensation.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 11 (Service Quality and Operation)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>As the Service is in the MVP stage, certain functions may be changed or deleted.</li>
        <li>
          In the event of major issues such as service failures, the Company may notify Members via
          pop-up or e-mail.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">Article 12 (Obligations of Members)</h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          The Member must provide all information accurately when using the Service and must comply
          with relevant laws and regulations.
        </li>
        <li>
          The Member must not engage in illegal acts, cause harm to others, or interfere with the
          normal operation of the Service..
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">
        Article 13 (Limitation of Liability of the Company)
      </h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>
          The Company is not liable for service interruptions caused by force majeure events such as
          natural disasters or communication network failures.
        </li>
        <li>
          The Company is not liable for problems caused by reasons attributable to the Member.
        </li>
        <li>
          The Company does not guarantee the accuracy, suitability, or completeness of AI Output,
          and the Member bears sole responsibility for acts based on the Output.
        </li>
      </ol>

      <h2 className="text-2xl font-extrabold mb-3">
        Article 14 (Consent to and Changes of Terms and Conditions)
      </h2>
      <ol className="list-decimal list-inside mb-6 space-y-3">
        <li>The Member must agree to these Terms and Conditions to use the Service.</li>
        <li>
          The Company may change the Terms and Conditions if necessary and will provide prior notice
          via pop-up or e-mail.
        </li>
        <li>
          The revised Terms and Conditions take effect after notice, and if the Member does not
          agree, they may request membership withdrawal.
        </li>
      </ol>
    </div>
  )
}

export default ServicePolicy
